#ifndef __OROGEN_TOOLKIT_<%= component.name.upcase %>_IDL__
#define __OROGEN_TOOLKIT_<%= component.name.upcase %>_IDL__

<% typekit.used_typekits.each do |tk| %>
#include <typekit/<%= tk.name %>Typekit.idl>
<% end %>

<%= minimal_registry.export 'idl',
	:namespace_prefix => 'orogen',
    :namespace_suffix => 'Corba',
    :opaque_as_any => true,
    :selected => typekit.self_typenames %>

#endif

