#ifndef __OROGEN_TOOLKIT_<%= typekit.name.upcase %>_IDL__
#define __OROGEN_TOOLKIT_<%= typekit.name.upcase %>_IDL__

<% typekit.used_typekits.each do |tk| %>
#include <<%= tk.name %>/transports/corba/<%= tk.name %>Types.idl>
<% end %>

<%= typesets.minimal_registry.export 'idl',
	:namespace_prefix => 'orogen',
    :namespace_suffix => 'Corba',
    :opaque_as_any => true,
    :selected => typekit.self_typenames %>

#endif

